### ISSUE TITLE
Vereinsadresse / Imprint

### ISSUE THREAD

**Issue by jjerlich** [BaselHack/www.baselhack.ch#14]
Wir hatten mal eine https://www.baselhack.ch/imprint mit der Adresse des Vereins / Vereinssitz - das braucht es auch wieder - ist vorgeschrieben. 
Bitte um die Wiederherstellung - hoffentlich gibt es noch eine alter Version, in der man nur die Adresse ändern muss.
Danke

**Comment by StanBarrows** [comment]
Hoi Jutta

Mir wurde beigebracht, dass Imprint => Terms ist. 

https://www.baselhack.ch/terms

**Comment by jjerlich** [comment]
Es braucht einen Platz für die Vereinsadresse als Verantwortlicher für die Seite, unter Kontakt ist auch gut. Irgendwo sollte es doch auf der Seite sein?
