### ISSUE TITLE
Update Laravel Nova 4.0

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/www.baselhack.ch#38]
- [x] Update Laravel Nova 4.0

- No Lock within composer Nova file makes update to 4.0

<img width="300" alt="CleanShot 2022-06-03 at 18 52 03@2x" src="https://user-images.githubusercontent.com/10268813/171910225-d9a45b95-86e9-40b7-a273-48f45d4a0cab.png">

@rordi Bist du noch im BaselHack Slack aktiv?

**Comment by rordi** [comment]
For now I locked the Nova <4.0 in the main / production branches.

**Comment by StanBarrows** [comment]
I've started a PR for this. Just Locking it to 4.0 does not solve the Problem. You need to Lock it to 3.0.

https://github.com/BaselHack/www.baselhack.ch/pull/39

**Comment by rordi** [comment]
Ok, I see. I will wait for you to complete the fix / PR then. So it means currently we can not deploy any changes to the website until we migrated to Nova 4.0? I locked to <4.0 - i.e. it is v3.32 that gets installed ( ``` - Locking laravel/nova (3.32.0```)), but this quick fix still does not work. 

It is a rather strange way for Laravel to update an auth mechanism in a way that lock deploy until you migrated...

**Comment by StanBarrows** [comment]
There is no lock in the deployment. There are some error in the code that causing the deployment script to fail.

- Missing compoer.lock
- Wrong version path to Nova in the composer file

Let me fix it quickly.

**Comment by StanBarrows** [comment]
@rordi 

<img width="1263" alt="CleanShot 2022-06-05 at 13 50 21@2x" src="https://user-images.githubusercontent.com/10268813/172049101-6e0130b4-6117-42bd-a6ba-a7a5682ae121.png">

**Comment by rordi** [comment]
Hi Stan @StanBarrows - ok, seems now after your fixes the deploy went through (the google verification tag is online). This is important, now we can apply some changes to the website in coming days, which is important as we need to communicate the new date, sponsors packages, etc. for this year's edition. Thanks a lot for you help! :)
