### ISSUE TITLE
Pages Update

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/www.baselhack.ch#56]
- [ ] Neue Seiten hinzufügen via Backend

![CleanShot 2022-08-18 at 12 51 35@2x](https://user-images.githubusercontent.com/10268813/185378160-82856abb-5b6c-4158-a475-b4aaef22451d.png)

**Comment by rordi** [comment]
@StanBarrows 

Ok, habe ich jetzt gemacht für "About". Den Button gab es heute morgen bei mir im UI noch nicht. Aber ein Problem bleibt: ich kann auch keine Section erstellen. Weil das Layout about aber Daten von der Section braucht (title & teaser), muss ich auch eine Section für "About" erstellen können.

**Comment by StanBarrows** [comment]
@rordi 

Ich habe es jetzt kurz via DB gemacht, bin leider nicht mehr am PC ab sofort.

In den Policies kannst du einstellen ob man ein Objekt Erstellen/Bearbeiten kann. app/Policies/SectionPolicy

<img width="1217" alt="CleanShot 2022-08-18 at 13 24 04@2x" src="https://user-images.githubusercontent.com/10268813/185383879-ca48490d-2c80-41d5-954d-a94dd9d572cf.png">
